import type { Routine } from "@shared/routine.ts";
import { resolveBinding } from "./resolve-binding.ts";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const FILE_HEADER =
  "<!-- Generated by Canon — do not edit by hand. Run /canon:routines sync to regenerate. -->";

// ---------------------------------------------------------------------------
// generateRoutinesIndex
// ---------------------------------------------------------------------------

/**
 * Generate the entire contents of `routines/.claude/CLAUDE.md`.
 *
 * Fully generated (no sentinel markers, no manual prose preservation).
 * Deterministic: same routines list → byte-identical output on every call.
 *
 * Per HITL decision (2026-06-08): the index is FULLY GENERATED — the old
 * sentinel-marker hybrid approach was overridden. The file header explicitly
 * says "do not edit by hand."
 *
 * Pure function — no I/O, no side effects (simplicity-first).
 */
export function generateRoutinesIndex(routines: Routine[]): string {
  const rows = routines
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((r) => {
      const binding = r.binding_target ?? resolveBinding(r.needs);
      const trigger =
        r.trigger.kind === "schedule" && r.trigger.cron
          ? `schedule(${r.trigger.cron})`
          : r.trigger.kind === "github-event" && r.trigger.event
            ? `github-event(${r.trigger.event})`
            : r.trigger.kind;
      return `| ${r.name} | ${r.status} | ${binding} | ${trigger} |`;
    })
    .join("\n");

  const table =
    rows.length > 0
      ? `| name | status | resolved binding | trigger |\n|------|--------|-----------------|--------|\n${rows}`
      : `| name | status | resolved binding | trigger |\n|------|--------|-----------------|--------|\n| — | — | — | — |`;

  const purpose =
    "Index of all Canon routines — automated tasks managed as first-class Canon artifacts.";

  return [
    FILE_HEADER,
    "",
    "# Canon Routines — Project Guidelines",
    "",
    purpose,
    "",
    table,
    "",
  ].join("\n");
}
