/** Canon PR Review View — Annotated diff viewer */

import { VERDICT_COLORS, SEVERITY_COLORS } from '../lib/theme.js';
import { createVerdictBadge } from '../components/filters.js';

export async function render(container) {
  container.innerHTML = `
    <div class="view-header">
      <h2>PR Review</h2>
      <div class="pr-input-bar">
        <input type="text" id="pr-number" placeholder="PR # or branch" class="search-input">
        <button id="load-pr" class="btn">Load Review</button>
      </div>
    </div>
    <div id="pr-content" class="pr-content">
      <p class="empty-state">Enter a PR number or branch name, then click Load Review.<br>
      Review data is generated by <code>/canon:pr-review</code>.</p>
    </div>
  `;

  const loadBtn = container.querySelector('#load-pr');
  const input = container.querySelector('#pr-number');
  const content = container.querySelector('#pr-content');

  loadBtn.addEventListener('click', async () => {
    const value = input.value.trim();
    if (!value) return;

    content.innerHTML = '<p class="loading">Loading review data...</p>';

    try {
      const resp = await fetch(`../.canon/pr-reviews/${value}/review-data.json`);
      if (!resp.ok) throw new Error('Not found');
      const data = await resp.json();
      renderReview(content, data);
    } catch {
      content.innerHTML = `
        <p class="empty-state">No review data for "${value}".<br>
        Run <code>/canon:pr-review ${value}</code> to generate.</p>
      `;
    }
  });
}

function renderReview(container, data) {
  const verdict = data.verdict || 'CLEAN';

  container.innerHTML = `
    <div class="review-summary">
      <div class="verdict-large" style="color: ${VERDICT_COLORS[verdict]}">${verdict}</div>
      <div class="score-grid">
        <div class="score-item">
          <label>Rules</label>
          <span>${data.score?.rules?.passed || 0}/${data.score?.rules?.total || 0}</span>
        </div>
        <div class="score-item">
          <label>Opinions</label>
          <span>${data.score?.opinions?.passed || 0}/${data.score?.opinions?.total || 0}</span>
        </div>
        <div class="score-item">
          <label>Conventions</label>
          <span>${data.score?.conventions?.passed || 0}/${data.score?.conventions?.total || 0}</span>
        </div>
      </div>
    </div>

    ${data.violations?.length > 0 ? `
      <div class="violations-section">
        <h3>Violations</h3>
        ${data.violations.map(v => `
          <div class="violation-item">
            <span class="severity-badge" style="background: ${SEVERITY_COLORS[v.severity] || '#7f8c8d'}">${v.severity}</span>
            <strong>${v.principle_id}</strong>
            ${v.file ? `<code>${v.file}</code>` : ''}
            ${v.detail ? `<p>${v.detail}</p>` : ''}
            ${v.suggestion ? `<p class="suggestion">Fix: ${v.suggestion}</p>` : ''}
          </div>
        `).join('')}
      </div>
    ` : ''}

    ${data.honored?.length > 0 ? `
      <div class="honored-section">
        <h3>Honored Principles</h3>
        <div class="honored-list">
          ${data.honored.map(id => `<span class="honored-chip">${id}</span>`).join('')}
        </div>
      </div>
    ` : ''}

    ${data.files?.length > 0 ? `
      <div class="files-section">
        <h3>Files Reviewed</h3>
        <ul class="file-list">
          ${data.files.map(f => `<li>${f}</li>`).join('')}
        </ul>
      </div>
    ` : ''}
  `;
}
