import type { Routine } from "@shared/routine.ts";
import { describe, expect, it } from "vitest";
import { generateRoutinesIndex } from "../services/routine-index.ts";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function makeRoutine(overrides: Partial<Routine> = {}): Routine {
  return {
    body: "",
    filePath: "/plugin/routines/test.md",
    guardrails: { consent: "opt-in", mutates_running_build: false, repo_writes: "none" },
    name: "test-routine",
    needs: { daemon: false, state: "git-native" },
    recurrence: "standing",
    repos: [],
    scope: "repo",
    source: "plugin",
    status: "enabled",
    title: "Test Routine",
    trigger: { kind: "schedule" },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Header and structure
// ---------------------------------------------------------------------------

describe("generateRoutinesIndex: structure", () => {
  it("starts with the fully-generated file header comment", () => {
    const output = generateRoutinesIndex([]);
    expect(output).toMatch(/<!-- Generated by Canon — do not edit by hand\./);
  });

  it("contains the title '# Canon Routines — Project Guidelines'", () => {
    const output = generateRoutinesIndex([]);
    expect(output).toContain("# Canon Routines — Project Guidelines");
  });

  it("contains a table with name, status, resolved binding, trigger columns", () => {
    const output = generateRoutinesIndex([]);
    expect(output).toContain("| name | status | resolved binding | trigger |");
  });

  it("ends with a trailing newline", () => {
    const output = generateRoutinesIndex([]);
    expect(output.endsWith("\n")).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Determinism and idempotency
// ---------------------------------------------------------------------------

describe("generateRoutinesIndex: determinism and idempotency", () => {
  it("is idempotent — same input produces byte-identical output on repeated calls", () => {
    const routines = [
      makeRoutine({ name: "alpha", status: "enabled" }),
      makeRoutine({ name: "beta", status: "disabled" }),
    ];
    const first = generateRoutinesIndex(routines);
    const second = generateRoutinesIndex(routines);
    expect(first).toBe(second);
  });

  it("produces deterministic output regardless of input order", () => {
    const r1 = makeRoutine({ name: "alpha" });
    const r2 = makeRoutine({ name: "beta" });
    const forwardOrder = generateRoutinesIndex([r1, r2]);
    const reverseOrder = generateRoutinesIndex([r2, r1]);
    expect(forwardOrder).toBe(reverseOrder);
  });

  it("does NOT contain 'Manual edits are preserved'", () => {
    const output = generateRoutinesIndex([makeRoutine()]);
    expect(output).not.toContain("Manual edits are preserved");
  });

  it("does NOT contain sentinel markers (fully generated, not hybrid)", () => {
    const output = generateRoutinesIndex([makeRoutine()]);
    expect(output).not.toContain("CANON:ROUTINES:START");
    expect(output).not.toContain("CANON:ROUTINES:END");
  });
});

// ---------------------------------------------------------------------------
// Table rows reflect routine status and binding
// ---------------------------------------------------------------------------

describe("generateRoutinesIndex: table content", () => {
  it("shows 'enabled' status in the table row", () => {
    const routine = makeRoutine({ name: "my-routine", status: "enabled" });
    const output = generateRoutinesIndex([routine]);
    expect(output).toContain("| my-routine | enabled |");
  });

  it("shows 'disabled' status in the table row", () => {
    const routine = makeRoutine({ name: "my-routine", status: "disabled" });
    const output = generateRoutinesIndex([routine]);
    expect(output).toContain("| my-routine | disabled |");
  });

  it("shows 'cloud-routine' binding for git-native non-daemon routine", () => {
    const routine = makeRoutine({
      name: "cloud-routine",
      needs: { daemon: false, state: "git-native" },
    });
    const output = generateRoutinesIndex([routine]);
    expect(output).toContain("| cloud-routine | enabled | cloud-routine |");
  });

  it("shows 'desktop-task' binding for daemon routine", () => {
    const routine = makeRoutine({
      name: "desktop-routine",
      needs: { daemon: true, state: "local-canon" },
    });
    const output = generateRoutinesIndex([routine]);
    expect(output).toContain("| desktop-routine | enabled | desktop-task |");
  });

  it("shows explicit binding_target override in the table", () => {
    const routine = makeRoutine({
      name: "override-routine",
      needs: { daemon: false, state: "git-native" },
      binding_target: "desktop-task",
    });
    const output = generateRoutinesIndex([routine]);
    expect(output).toContain("| override-routine | enabled | desktop-task |");
  });

  it("shows schedule trigger with cron expression", () => {
    const routine = makeRoutine({
      name: "cron-routine",
      trigger: { kind: "schedule", cron: "0 * * * *" },
    });
    const output = generateRoutinesIndex([routine]);
    expect(output).toContain("schedule(0 * * * *)");
  });

  it("shows github-event trigger with event name", () => {
    const routine = makeRoutine({
      name: "event-routine",
      trigger: { kind: "github-event", event: "pull_request" },
    });
    const output = generateRoutinesIndex([routine]);
    expect(output).toContain("github-event(pull_request)");
  });

  it("shows bare trigger kind when no cron/event suffix", () => {
    const routine = makeRoutine({
      name: "bare-trigger",
      trigger: { kind: "api" },
    });
    const output = generateRoutinesIndex([routine]);
    expect(output).toContain("| api |");
  });

  it("reflects status change when routine status changes", () => {
    const before = makeRoutine({ name: "routine-a", status: "enabled" });
    const after = { ...before, status: "disabled" as const };
    const beforeOutput = generateRoutinesIndex([before]);
    const afterOutput = generateRoutinesIndex([after]);
    expect(beforeOutput).toContain("enabled");
    expect(afterOutput).toContain("disabled");
    expect(beforeOutput).not.toBe(afterOutput);
  });

  it("reflects binding change when routine binding changes", () => {
    const before = makeRoutine({
      name: "routine-b",
      needs: { daemon: false, state: "git-native" },
    });
    const after = { ...before, needs: { daemon: true, state: "local-canon" as const } };
    const beforeOutput = generateRoutinesIndex([before]);
    const afterOutput = generateRoutinesIndex([after]);
    expect(beforeOutput).toContain("cloud-routine");
    expect(afterOutput).toContain("desktop-task");
  });

  it("shows empty table placeholder row when there are no routines", () => {
    const output = generateRoutinesIndex([]);
    expect(output).toContain("| — | — | — | — |");
  });

  it("includes all routines in the table", () => {
    const routines = [
      makeRoutine({ name: "alpha" }),
      makeRoutine({ name: "beta" }),
      makeRoutine({ name: "gamma" }),
    ];
    const output = generateRoutinesIndex(routines);
    expect(output).toContain("alpha");
    expect(output).toContain("beta");
    expect(output).toContain("gamma");
  });
});
